### ISSUE TITLE
initial to-dos

### ISSUE THREAD

**Issue by startakovsky** [startakovsky/kaggle-digit-recognizer#1]
- [x] Dockerfile Cleanup
  - [x] Python 3.5
  - [x] Dependencies
    - [x] scikit-learn
    - [x] PyMC 3
    - [x] Pandas 
    - [x] no neural networks on first pass -- keep it simple
- [x] README.md Instructions
  - [ ] Pull Request Process (for merging)
  - [x] Environment Setup
    - [x] Create Name Folder
  - [x] pip-tools
  - [ ] [requirements.py](https://github.com/socketubs/requirements / requirements.txt

**Comment by ghost** [comment]
Your picture is homosexual.

**Comment by startakovsky** [comment]
I find your comment disrespectful.

![image](https://cloud.githubusercontent.com/assets/689723/14972775/8aef6d54-1094-11e6-88c1-68f899f0b069.png)
